server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/chunin_exam?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root

jwt:
  config:
    type: signed

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app: Chunin Exam - Auth Microservice
  github: https://github.com/HarissonNascimento/chunin-exam-with-microservices
  developer: Harisson Nascimento
  linkedin: https://www.linkedin.com/in/harisson-nascimento/

